# Generated by Django 3.2.23 on 2024-01-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0002_auto_20240101_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
