# Generated by Django 3.2.23 on 2024-01-13 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0003_auto_20240101_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(choices=[('Mobiles', 'Mobiles'), ('Televisions', 'Televisions'), ('Laptops', 'Laptops'), ('Cameras', 'Cameras'), ('Audio', 'Audio'), ('Appliances', 'Appliances')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eadmin.brand')),
            ],
        ),
    ]
