# Generated by Django 3.2.23 on 2024-01-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0004_brand_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
