# Generated by Django 3.2.23 on 2024-01-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0005_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=10),
        ),
    ]
